spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  application:
    name: webflux

logging:
  level:
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor: DEBUG